apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
      role: auth-api
  template:
    metadata:
      labels:
        app: auth-api
        role: auth-api
    spec:
      containers:
      - name: auth-api
        image: demo-image
        imagePullPolicy: Never #Never para trabajar con images docker local; Always images de dockerhub
        resources: # pendiente de verificación
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe: # pendiente de verificación
          tcpSocket:
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: service-auth-api
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    role: auth-api